{% set name = "sqlalchemy-views" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c396416939bc4459c71f15c0279b72c9eb1f92fe022afe7fa74ed3adeef76e3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.0.0

test:
  imports:
    - sqlalchemy_views
  requires:
    - pip
    - sqlalchemy >=1.0.0
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jklukas/sqlalchemy-views
  summary: Adds CreateView and DropView constructs to SQLAlchemy.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
